from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import JSON, Boolean, DateTime, Enum, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class ActionStatus(str, enum.Enum):
    """Lifecycle of a single cell-level mutation.

    - APPLIED: the write hit the workbook and the audit row is authoritative
    - PENDING_APPROVAL: the orchestrator staged the action because it would
      overwrite user data; the workbook was NOT modified
    - REJECTED: user (or the system) declined a pending approval; terminal
    - UNDONE: Stage 5 inverse-applied this action; terminal

    See docs/decisions/0002-schema-consolidation.md for the state machine.
    """

    APPLIED = "applied"
    PENDING_APPROVAL = "pending_approval"
    REJECTED = "rejected"
    UNDONE = "undone"


class OrchestratorStateEnum(str, enum.Enum):
    """Stage 6 durable-execution state machine.

    PLANNING → EXECUTING → VERIFYING → DONE
        └────────┴────────────┴──► FAILED

    See docs/decisions/0003-durable-execution.md.
    """

    PLANNING = "planning"
    EXECUTING = "executing"
    VERIFYING = "verifying"
    DONE = "done"
    FAILED = "failed"


class Session(Base):
    __tablename__ = "sessions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title: Mapped[str | None] = mapped_column(String(256), nullable=True)
    # `workbook_path` is the current working copy the orchestrator reads
    # and overwrites. `original_workbook_path` is the immutable snapshot
    # saved on upload — so Stage 5's replay can reconstruct from it.
    workbook_path: Mapped[str] = mapped_column(String(512))
    original_workbook_path: Mapped[str | None] = mapped_column(String(512), nullable=True)
    # Populated in Stage 8; nullable no-op until then.
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    actions: Mapped[list[Action]] = relationship(
        back_populates="session", cascade="all, delete-orphan", order_by="Action.sequence"
    )


class Action(Base):
    """Cell-level audit log. Each row is one atomic mutation (or proposed
    mutation) against the workbook.

    See docs/decisions/0002-schema-consolidation.md for how the columns
    partition across Stages 3, 5, and 8.
    """

    __tablename__ = "actions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("sessions.id", ondelete="CASCADE"), index=True
    )
    sequence: Mapped[int] = mapped_column()

    # Stable identity across branches and replays. Generated by the
    # domain Action at emission time, preserved through persistence.
    # See docs/decisions/0002-schema-consolidation.md → Stage 5 erratum.
    client_action_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), index=True
    )

    agent: Mapped[str] = mapped_column(String(64))
    action_type: Mapped[str] = mapped_column(String(64))

    sheet: Mapped[str | None] = mapped_column(String(255), nullable=True)
    target_range: Mapped[str | None] = mapped_column(String(255), nullable=True)

    previous_value: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    new_value: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Stage 3 — approval flow.
    status: Mapped[ActionStatus] = mapped_column(
        Enum(ActionStatus, name="action_status", values_callable=lambda e: [x.value for x in e]),
        default=ActionStatus.APPLIED,
        server_default=ActionStatus.APPLIED.value,
        index=True,
    )
    approval_required_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    force_override: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false"
    )

    # Stage 5 — branching (nullable; populated when sessions are forked).
    parent_action_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("actions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Stage 8 — tenant isolation + audit attribution. Nullable no-ops
    # until Stage 8 populates them from JWT claims.
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True, index=True
    )
    user_sub: Mapped[str | None] = mapped_column(String(256), nullable=True)

    session: Mapped[Session] = relationship(back_populates="actions")


class SessionBranch(Base):
    """Lineage edge between two sessions.

    Branching creates a new Session whose initial state is the parent's
    state at `branched_at_sequence`. Actions up to that sequence are
    copied to the child with matching `client_action_id` values but new
    DB row ids. Subsequent actions on either branch are independent.

    Stored as a separate table rather than a `parent_session_id` column
    on `sessions` so Stage 3's consolidated schema and Stage 8's RLS
    policies on `sessions` don't have to accommodate a retroactive
    column add (see docs/decisions/0002-schema-consolidation.md).
    """

    __tablename__ = "session_branches"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    child_session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("sessions.id", ondelete="CASCADE"), unique=True
    )
    parent_session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("sessions.id", ondelete="CASCADE"), index=True
    )
    branched_at_sequence: Mapped[int] = mapped_column()
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class OrchestratorState(Base):
    """Per-session durable state for the Stage 6 orchestrator.

    One row per active session. Survives worker restarts — on boot the
    app scans this table for non-terminal states and resumes them.
    See docs/decisions/0003-durable-execution.md for the state machine
    and checkpoint semantics.
    """

    __tablename__ = "orchestrator_states"

    # One-to-one with sessions: the session id is the natural primary key.
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sessions.id", ondelete="CASCADE"),
        primary_key=True,
    )
    state: Mapped[OrchestratorStateEnum] = mapped_column(
        Enum(
            OrchestratorStateEnum,
            name="orchestrator_state",
            values_callable=lambda e: [x.value for x in e],
        ),
        index=True,
    )
    # The original user prompt — preserved so resume can replay planning
    # if needed. Plans are currently cached on successful PLANNING, so
    # resume after that state is cheap.
    prompt: Mapped[str] = mapped_column(Text)
    # Serialized Plan (from agents.planner.Plan.model_dump()). None until
    # the planning step has produced one.
    plan: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    # Next plan-step index to execute. After step K completes, this is
    # incremented to K+1 and the row is committed.
    current_step_index: Mapped[int] = mapped_column(default=0, server_default="0")
    # Populated when state=FAILED; stays null on happy-path completion.
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
